// GENERATED by site/test/gen-mark.mjs from site/test/icon-1024.png —
// the same contour the favicon and the page's inline logo are cut from, and the
// same pixels Magnetite.icns is built from. portcheck re-derives all three and
// asserts each is what the derivation produces.
//
// Do not edit. Change the icon master, or the generator, and re-run:
//   node site/test/gen-mark.mjs

import AppKit

/// The poured M, as geometry rather than as a picture of geometry.
enum MagnetiteMark {
    /// Width over height of the ink, so a caller can size a box for it.
    static let aspect: CGFloat = 1.44132

    /// The mark in a unit box, y up — ready to be scaled into any rect.
    static func path() -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 0.13795, y: 0.99922))
        path.addCurve(to: CGPoint(x: 0.16598, y: 0.99303),
                      control1: CGPoint(x: 0.14694, y: 1.00190),
                      control2: CGPoint(x: 0.15747, y: 0.99715))
        path.addCurve(to: CGPoint(x: 0.22207, y: 0.93684),
                      control1: CGPoint(x: 0.18713, y: 0.98280),
                      control2: CGPoint(x: 0.20591, y: 0.95827))
        path.addCurve(to: CGPoint(x: 0.23723, y: 0.91547),
                      control1: CGPoint(x: 0.22725, y: 0.92997),
                      control2: CGPoint(x: 0.23177, y: 0.92190))
        path.addCurve(to: CGPoint(x: 0.26300, y: 0.88017),
                      control1: CGPoint(x: 0.24644, y: 0.90462),
                      control2: CGPoint(x: 0.25449, y: 0.89216))
        path.addCurve(to: CGPoint(x: 0.27209, y: 0.86911),
                      control1: CGPoint(x: 0.26585, y: 0.87614),
                      control2: CGPoint(x: 0.26916, y: 0.87300))
        path.addCurve(to: CGPoint(x: 0.29259, y: 0.83973),
                      control1: CGPoint(x: 0.27918, y: 0.85971),
                      control2: CGPoint(x: 0.28564, y: 0.84934))
        path.addCurve(to: CGPoint(x: 0.30161, y: 0.82881),
                      control1: CGPoint(x: 0.29544, y: 0.83580),
                      control2: CGPoint(x: 0.29876, y: 0.83274))
        path.addCurve(to: CGPoint(x: 0.38729, y: 0.71181),
                      control1: CGPoint(x: 0.33002, y: 0.78953),
                      control2: CGPoint(x: 0.35834, y: 0.75020))
        path.addCurve(to: CGPoint(x: 0.41457, y: 0.67442),
                      control1: CGPoint(x: 0.39656, y: 0.69951),
                      control2: CGPoint(x: 0.40480, y: 0.68592))
        path.addCurve(to: CGPoint(x: 0.42670, y: 0.65741),
                      control1: CGPoint(x: 0.41893, y: 0.66928),
                      control2: CGPoint(x: 0.42256, y: 0.66290))
        path.addCurve(to: CGPoint(x: 0.48885, y: 0.60357),
                      control1: CGPoint(x: 0.44518, y: 0.63291),
                      control2: CGPoint(x: 0.46358, y: 0.61088))
        path.addCurve(to: CGPoint(x: 0.50704, y: 0.60276),
                      control1: CGPoint(x: 0.49466, y: 0.60189),
                      control2: CGPoint(x: 0.50114, y: 0.60239))
        path.addCurve(to: CGPoint(x: 0.57373, y: 0.65741),
                      control1: CGPoint(x: 0.53360, y: 0.60444),
                      control2: CGPoint(x: 0.55530, y: 0.63297))
        path.addCurve(to: CGPoint(x: 0.58586, y: 0.67442),
                      control1: CGPoint(x: 0.57787, y: 0.66290),
                      control2: CGPoint(x: 0.58150, y: 0.66928))
        path.addCurve(to: CGPoint(x: 0.61314, y: 0.71181),
                      control1: CGPoint(x: 0.59563, y: 0.68592),
                      control2: CGPoint(x: 0.60387, y: 0.69951))
        path.addCurve(to: CGPoint(x: 0.67003, y: 0.78948),
                      control1: CGPoint(x: 0.63237, y: 0.73731),
                      control2: CGPoint(x: 0.65115, y: 0.76339))
        path.addCurve(to: CGPoint(x: 0.67904, y: 0.80040),
                      control1: CGPoint(x: 0.67287, y: 0.79341),
                      control2: CGPoint(x: 0.67620, y: 0.79647))
        path.addCurve(to: CGPoint(x: 0.75643, y: 0.90746),
                      control1: CGPoint(x: 0.70487, y: 0.83610),
                      control2: CGPoint(x: 0.73060, y: 0.87176))
        path.addCurve(to: CGPoint(x: 0.76699, y: 0.92057),
                      control1: CGPoint(x: 0.75979, y: 0.91211),
                      control2: CGPoint(x: 0.76367, y: 0.91582))
        path.addCurve(to: CGPoint(x: 0.78350, y: 0.94241),
                      control1: CGPoint(x: 0.77236, y: 0.92823),
                      control2: CGPoint(x: 0.77786, y: 0.93523))
        path.addCurve(to: CGPoint(x: 0.87992, y: 0.99328),
                      control1: CGPoint(x: 0.80945, y: 0.97549),
                      control2: CGPoint(x: 0.84286, y: 1.01492))
        path.addCurve(to: CGPoint(x: 0.89357, y: 0.98243),
                      control1: CGPoint(x: 0.88469, y: 0.99050),
                      control2: CGPoint(x: 0.88949, y: 0.98699))
        path.addCurve(to: CGPoint(x: 0.92449, y: 0.88561),
                      control1: CGPoint(x: 0.91434, y: 0.95922),
                      control2: CGPoint(x: 0.92222, y: 0.92195))
        path.addCurve(to: CGPoint(x: 0.92469, y: 0.85721),
                      control1: CGPoint(x: 0.92508, y: 0.87620),
                      control2: CGPoint(x: 0.92441, y: 0.86665))
        path.addCurve(to: CGPoint(x: 0.92610, y: 0.84191),
                      control1: CGPoint(x: 0.92485, y: 0.85203),
                      control2: CGPoint(x: 0.92594, y: 0.84709))
        path.addCurve(to: CGPoint(x: 0.92616, y: 0.76326),
                      control1: CGPoint(x: 0.92690, y: 0.81580),
                      control2: CGPoint(x: 0.92616, y: 0.78941))
        path.addCurve(to: CGPoint(x: 0.92616, y: 0.60815),
                      control1: CGPoint(x: 0.92616, y: 0.71156),
                      control2: CGPoint(x: 0.92616, y: 0.65985))
        path.addCurve(to: CGPoint(x: 0.93071, y: 0.50328),
                      control1: CGPoint(x: 0.92616, y: 0.57349),
                      control2: CGPoint(x: 0.92331, y: 0.53671))
        path.addCurve(to: CGPoint(x: 0.95268, y: 0.44470),
                      control1: CGPoint(x: 0.93543, y: 0.48198),
                      control2: CGPoint(x: 0.94445, y: 0.46341))
        path.addCurve(to: CGPoint(x: 0.97948, y: 0.37219),
                      control1: CGPoint(x: 0.96277, y: 0.42177),
                      control2: CGPoint(x: 0.97274, y: 0.39761))
        path.addCurve(to: CGPoint(x: 0.96246, y: 0.06633),
                      control1: CGPoint(x: 1.00476, y: 0.27692),
                      control2: CGPoint(x: 1.01442, y: 0.14773))
        path.addCurve(to: CGPoint(x: 0.92388, y: 0.02293),
                      control1: CGPoint(x: 0.95106, y: 0.04847),
                      control2: CGPoint(x: 0.93850, y: 0.03481))
        path.addCurve(to: CGPoint(x: 0.88144, y: 0.00235),
                      control1: CGPoint(x: 0.91111, y: 0.01255),
                      control2: CGPoint(x: 0.89592, y: 0.00547))
        path.addCurve(to: CGPoint(x: 0.73341, y: 0.12532),
                      control1: CGPoint(x: 0.81888, y: -0.01114),
                      control2: CGPoint(x: 0.75726, y: 0.04119))
        path.addCurve(to: CGPoint(x: 0.72158, y: 0.24548),
                      control1: CGPoint(x: 0.72271, y: 0.16307),
                      control2: CGPoint(x: 0.72035, y: 0.20515))
        path.addCurve(to: CGPoint(x: 0.73006, y: 0.31539),
                      control1: CGPoint(x: 0.72229, y: 0.26876),
                      control2: CGPoint(x: 0.72610, y: 0.29284))
        path.addCurve(to: CGPoint(x: 0.74772, y: 0.39186),
                      control1: CGPoint(x: 0.73463, y: 0.34142),
                      control2: CGPoint(x: 0.73963, y: 0.36757))
        path.addCurve(to: CGPoint(x: 0.78183, y: 0.47488),
                      control1: CGPoint(x: 0.75741, y: 0.42093),
                      control2: CGPoint(x: 0.77073, y: 0.44699))
        path.addCurve(to: CGPoint(x: 0.79308, y: 0.57538),
                      control1: CGPoint(x: 0.79381, y: 0.50496),
                      control2: CGPoint(x: 0.79698, y: 0.54138))
        path.addCurve(to: CGPoint(x: 0.77685, y: 0.62193),
                      control1: CGPoint(x: 0.79109, y: 0.59270),
                      control2: CGPoint(x: 0.78699, y: 0.61086))
        path.addCurve(to: CGPoint(x: 0.74502, y: 0.62222),
                      control1: CGPoint(x: 0.76718, y: 0.63249),
                      control2: CGPoint(x: 0.75526, y: 0.62878))
        path.addCurve(to: CGPoint(x: 0.69197, y: 0.56117),
                      control1: CGPoint(x: 0.72466, y: 0.60919),
                      control2: CGPoint(x: 0.70747, y: 0.58352))
        path.addCurve(to: CGPoint(x: 0.67832, y: 0.54359),
                      control1: CGPoint(x: 0.68760, y: 0.55489),
                      control2: CGPoint(x: 0.68284, y: 0.54957))
        path.addCurve(to: CGPoint(x: 0.62207, y: 0.45740),
                      control1: CGPoint(x: 0.66029, y: 0.51968),
                      control2: CGPoint(x: 0.63605, y: 0.48585))
        path.addCurve(to: CGPoint(x: 0.52978, y: 0.30922),
                      control1: CGPoint(x: 0.59479, y: 0.40190),
                      control2: CGPoint(x: 0.57862, y: 0.33355))
        path.addCurve(to: CGPoint(x: 0.50552, y: 0.30140),
                      control1: CGPoint(x: 0.52202, y: 0.30536),
                      control2: CGPoint(x: 0.51371, y: 0.30247))
        path.addCurve(to: CGPoint(x: 0.47975, y: 0.30530),
                      control1: CGPoint(x: 0.49695, y: 0.30029),
                      control2: CGPoint(x: 0.48807, y: 0.30238))
        path.addCurve(to: CGPoint(x: 0.46005, y: 0.31594),
                      control1: CGPoint(x: 0.47284, y: 0.30773),
                      control2: CGPoint(x: 0.46640, y: 0.31138))
        path.addCurve(to: CGPoint(x: 0.37837, y: 0.45740),
                      control1: CGPoint(x: 0.41809, y: 0.34607),
                      control2: CGPoint(x: 0.40383, y: 0.40560))
        path.addCurve(to: CGPoint(x: 0.32211, y: 0.54359),
                      control1: CGPoint(x: 0.36439, y: 0.48585),
                      control2: CGPoint(x: 0.34014, y: 0.51968))
        path.addCurve(to: CGPoint(x: 0.30999, y: 0.55899),
                      control1: CGPoint(x: 0.31812, y: 0.54887),
                      control2: CGPoint(x: 0.31384, y: 0.55344))
        path.addCurve(to: CGPoint(x: 0.26223, y: 0.61689),
                      control1: CGPoint(x: 0.29540, y: 0.58000),
                      control2: CGPoint(x: 0.28020, y: 0.60190))
        path.addCurve(to: CGPoint(x: 0.23571, y: 0.62868),
                      control1: CGPoint(x: 0.25433, y: 0.62347),
                      control2: CGPoint(x: 0.24511, y: 0.62989))
        path.addCurve(to: CGPoint(x: 0.21021, y: 0.59285),
                      control1: CGPoint(x: 0.22233, y: 0.62695),
                      control2: CGPoint(x: 0.21423, y: 0.60962))
        path.addCurve(to: CGPoint(x: 0.21342, y: 0.49017),
                      control1: CGPoint(x: 0.20273, y: 0.56167),
                      control2: CGPoint(x: 0.20476, y: 0.52042))
        path.addCurve(to: CGPoint(x: 0.24784, y: 0.40493),
                      control1: CGPoint(x: 0.22213, y: 0.45977),
                      control2: CGPoint(x: 0.23758, y: 0.43424))
        path.addCurve(to: CGPoint(x: 0.27876, y: 0.24766),
                      control1: CGPoint(x: 0.26484, y: 0.35635),
                      control2: CGPoint(x: 0.27537, y: 0.30188))
        path.addCurve(to: CGPoint(x: 0.20236, y: 0.02212),
                      control1: CGPoint(x: 0.28431, y: 0.15904),
                      control2: CGPoint(x: 0.25939, y: 0.06433))
        path.addCurve(to: CGPoint(x: 0.15992, y: 0.00235),
                      control1: CGPoint(x: 0.18942, y: 0.01254),
                      control2: CGPoint(x: 0.17431, y: 0.00545))
        path.addCurve(to: CGPoint(x: 0.15083, y: 0.00141),
                      control1: CGPoint(x: 0.15691, y: 0.00170),
                      control2: CGPoint(x: 0.15384, y: 0.00205))
        path.addCurve(to: CGPoint(x: 0.09626, y: 0.01066),
                      control1: CGPoint(x: 0.13293, y: -0.00243),
                      control2: CGPoint(x: 0.11332, y: 0.00189))
        path.addCurve(to: CGPoint(x: 0.05962, y: 0.03793),
                      control1: CGPoint(x: 0.08330, y: 0.01733),
                      control2: CGPoint(x: 0.07071, y: 0.02608))
        path.addCurve(to: CGPoint(x: 0.00006, y: 0.20834),
                      control1: CGPoint(x: 0.02258, y: 0.07750),
                      control2: CGPoint(x: 0.00206, y: 0.14260))
        path.addCurve(to: CGPoint(x: 0.00147, y: 0.24329),
                      control1: CGPoint(x: -0.00030, y: 0.22029),
                      control2: CGPoint(x: 0.00111, y: 0.23153))
        path.addCurve(to: CGPoint(x: 0.02155, y: 0.37438),
                      control1: CGPoint(x: 0.00280, y: 0.28712),
                      control2: CGPoint(x: 0.01008, y: 0.33352))
        path.addCurve(to: CGPoint(x: 0.04775, y: 0.44470),
                      control1: CGPoint(x: 0.02845, y: 0.39895),
                      control2: CGPoint(x: 0.03792, y: 0.42235))
        path.addCurve(to: CGPoint(x: 0.07105, y: 0.50983),
                      control1: CGPoint(x: 0.05682, y: 0.46532),
                      control2: CGPoint(x: 0.06681, y: 0.48584))
        path.addCurve(to: CGPoint(x: 0.07428, y: 0.58848),
                      control1: CGPoint(x: 0.07562, y: 0.53561),
                      control2: CGPoint(x: 0.07428, y: 0.56207))
        path.addCurve(to: CGPoint(x: 0.07428, y: 0.70646),
                      control1: CGPoint(x: 0.07428, y: 0.62781),
                      control2: CGPoint(x: 0.07428, y: 0.66713))
        path.addCurve(to: CGPoint(x: 0.07433, y: 0.84191),
                      control1: CGPoint(x: 0.07428, y: 0.75147),
                      control2: CGPoint(x: 0.07297, y: 0.79695))
        path.addCurve(to: CGPoint(x: 0.07574, y: 0.85721),
                      control1: CGPoint(x: 0.07449, y: 0.84709),
                      control2: CGPoint(x: 0.07558, y: 0.85203))
        path.addCurve(to: CGPoint(x: 0.07594, y: 0.88561),
                      control1: CGPoint(x: 0.07603, y: 0.86665),
                      control2: CGPoint(x: 0.07535, y: 0.87620))
        path.addCurve(to: CGPoint(x: 0.11293, y: 0.98850),
                      control1: CGPoint(x: 0.07832, y: 0.92349),
                      control2: CGPoint(x: 0.08801, y: 0.96895))
        path.addCurve(to: CGPoint(x: 0.13795, y: 0.99922),
                      control1: CGPoint(x: 0.12109, y: 0.99490),
                      control2: CGPoint(x: 0.12906, y: 0.99656))
        path.closeSubpath()
        return path
    }

    /// A menu-bar image: drawn at the height asked for, and a TEMPLATE, so the
    /// system inverts it for a dark menu bar and dims it when the app is not
    /// active instead of leaving a black mark on a black bar.
    static func menuBarImage(height: CGFloat) -> NSImage {
        let size = NSSize(width: (height * aspect).rounded(), height: height)
        let image = NSImage(size: size, flipped: false) { rect in
            guard let context = NSGraphicsContext.current?.cgContext else { return false }
            var scale = CGAffineTransform(scaleX: rect.width, y: rect.height)
            guard let scaled = path().copy(using: &scale) else { return false }
            context.addPath(scaled)
            context.setFillColor(NSColor.black.cgColor)
            context.fillPath()
            return true
        }
        image.isTemplate = true
        return image
    }
}
